config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Remove the path_names section entirely, or use it correctly like:
  # path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  devise_for :admins, skip: [:registrations], path: 'admins', path_names: {
    sign_in: 'sign_in',
    sign_out: 'sign_out'
  }, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    root to: 'dashboards#index' 
    resources :orders
    resources :products 
    resources :collections
    resources :categories
    resources :conversations, only: [:index, :show]
    resources :customers, only: [:index, :show]
  end

  root 'homes#index'
  resources :products, only: [:show]
  resources :collections, only: [:show]
  resources :categories, only: [:show]
  resources :line_items, only: [:create, :show, :update, :destroy]
  resources :wishlists, only: [:index]
  resources :wishlist_items, only: [:create, :destroy]
  resources :billing_details
  resources :carts, only: [:index]
  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
  get 'start_chat', to: 'conversations#create', as: :start_chat
  post "/place_order", to: "orders#place_order"

  resources :orders do
    collection do
      get :success
      get :cancel
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category , required: true
    has_many :product_variants
    has_many :product_variant_combinations 
    has_many :wishlist_items
    has_many :wishlists, through: :wishlist_items
    has_and_belongs_to_many :collections , join_table: "collections_products_join_table"
    has_one_attached :featured_image
    accepts_nested_attributes_for :product_variants, allow_destroy: true
    accepts_nested_attributes_for :product_variant_combinations, allow_destroy: true

    validates :name, presence: true 
    validates :brand, presence:true 
    validates :description , length: {maximum: 1000}
    validates :specification , length: {maximum: 2000}
    validates :short_description , length: {maximum: 500}
    validates :featured , inclusion: { in: [true, false]} 
    validates :slug , presence: true , uniqueness: true 
      
     def default_variant_combination
         product_variant_combinations.order(:id).first
     end

    def variant_groups
        product_variants.group_by(&:variant_type)
    end

     
    def to_param
        slug
    end

   def self.ransackable_associations(auth_object = nil)
  ["product_variant_combinations", "category", "collections"]
end

end

app/controllers/admins/products_controller.rb
module Admins
    class ProductsController < Admins::ApplicationController
        before_action :set_product, only: [:edit, :update, :show, :inventory]

        def index 
          @products = Product.includes(:category).all
        end
        
        def new
          @product = Product.new
          @product.product_variants.build 
        end

         def create
         @product = Product.new(product_params)
        if @product.save

             prices = params[:product][:combination_prices]
             stocks = params[:product][:combination_stock]
            compared  = params[:product][:combination_compared_prices]

            groups = @product.variant_groups.values
            combinations = groups.shift.product(*groups)

             combinations.each_with_index do |variants, index|
      pvc = @product.product_variant_combinations.create!(
        price: prices[index],
        compared_price: compared[index],
       stock_qunatity: stocks[index]
      )
      pvc.product_variants << variants
    end
            redirect_to admins_products_path, notice: "Product created!"
        else
            render :new
        end
        end
        
        def edit 
          @product = Product.find_by!(slug: params[:id])
        end 
  
        def update
  # Find the product
  @product = Product.find_by!(slug: params[:id])

  if @product.update(product_params)
    if params[:product][:featured_image].present?
      @product.featured_image.attach(params[:product][:featured_image])
    end
    # Handle combination prices / stock / compared prices if sent
    prices  = params[:product][:combination_prices] || []
    compare = params[:product][:combination_compared_prices] || []
    stocks  = params[:product][:combination_stock] || []

    # Generate combinations (similar to create)
    groups = @product.variant_groups.values
    combinations = groups.shift.product(*groups)

    combinations.each_with_index do |variants, index|
      # Find existing combination or create new
      pvc = @product.product_variant_combinations.find_or_initialize_by(
        product_variants: variants
      )

      pvc.price          = prices[index]
      pvc.compared_price = compare[index]
      pvc.stock_quantity = stocks[index]
      pvc.save!
    end

    redirect_to admins_product_path(@product), notice: "Product updated!"
  else
    # If update fails, re-render form with errors
    render :edit
  end
end

        def destroy
        end 

        private

         def set_product
         @product = Product.find_by!(slug: params[:id])
         end


        def product_params
      params.require(:product).permit(
        :name,
        :description,
        :slug,
        :short_description,
        :brand,
        :category_id,
        :featured,
        :featured_image,
        product_variants_attributes: [
          :id,
          :variant_type,
          :value,
          :_destroy
        ]
      )
    end
        
    end
end

app/controllers/products_controller.rb
class ProductsController <  ApplicationController
    def show
  @product = Product
    .includes(
      :product_variants,
      product_variant_combinations: :product_variants,
      featured_image_attachment: :blob
    )
    .find_by(slug: params[:id])

  unless @product
    redirect_to products_path, alert: "Product not found"
    return
  end

  # All available variant options (Size, Color, etc.)
  @variant_options = @product.product_variants.group_by(&:variant_type)

  # All variant combinations (SKU-level)
  @variant_combinations = @product.product_variant_combinations

  # Related products
  @related_products = Product
    .includes(:featured_image_attachment)
    .where(category_id: @product.category_id)
    .where.not(id: @product.id)
    .limit(4)

    respond_to do |format|
    format.html # default show.html.erb
    format.js   # renders show.js.erb
  end
end
                                                    
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/show.html.erb
 <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                        <a href="#"><%= @product.category.name %></a>
                        <span><%= @product.name %></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Product Details Section Begin -->
    <section class="product-details spad">
  <div class="container">
    <div class="row">

      <!-- Product Images -->
      <div class="col-lg-6">
        <div class="product__details__pic">
          <div class="product__details__pic__left product__thumb nice-scroll">
          <div class="product__details__pic__item">
  <% if @product.featured_image.attached? %>
    <%= image_tag @product.featured_image,
          alt: @product.name,
          id: "main-product-image",
          class: "img-fluid" %>
  <% else %>
    <%= image_tag "default-product.jpg",
          alt: @product.name,
          id: "main-product-image",
          class: "img-fluid" %>
  <% end %>
</div>
            
          </div>

          <div class="product__details__slider__content">
            <div class="product__details__pic__slider owl-carousel">
              <div class="product__details__pic__item">
  <% if @product.featured_image.attached? %>
    <%= image_tag @product.featured_image,
          alt: @product.name,
          id: "main-product-image",
          class: "img-fluid" %>
  <% else %>
    <%= image_tag "default-product.jpg",
          alt: @product.name,
          id: "main-product-image",
          class: "img-fluid" %>
  <% end %>
</div>
            </div>
          </div>
        </div>
      </div>

      <!-- Product Info -->
      <div class="col-lg-6">
        <div class="product__details__text">
          <h3><%= @product.name %> <span>Brand: <%= @product.brand %></span></h3>

          <div class="rating">
            <% 5.times do %>
              <i class="fa fa-star"></i>
            <% end %>
            <span>( 138 reviews )</span>
          </div>

          <% default_combination = @variant_combinations.first %>

         <div class="product__details__price">
          $ <div id="product-price" style="display:inline"><%= default_combination.price %></div>

          <span id="compared-price">
            <% if default_combination.compared_price.present? &&
                  default_combination.compared_price > default_combination.price %>
              $ <%= default_combination.compared_price %>
            <% end %>
          </span>
        </div>

          <p><%= @product.short_description %></p>

          <!-- Add to Cart Form -->
          <div class="product__details__button">
            <%= form_with url: line_items_path, method: :post, local: true, id: "add-to-cart-form" do |f| %>
              <div class="quantity">
                <span>Quantity:</span>
                <div class="pro-qty">
                  <%= f.number_field :quantity, value: 1, min: 1, class: "quantity-input" %>
                </div>
              </div>

              <!-- Hidden field for variant -->
             <%= f.hidden_field :product_variant_combination_id,
      id: "selected-variant-id",
      value: default_combination.id %>


              <%= f.submit "Add to cart", class: "cart-btn" %>
<% end %>
              <ul>
  <li>
    <%= link_to wishlist_items_path(product_id: @product.id),
              method: :post,
              remote: true,
              class: "wishlist-btn",
              form: { data: { turbo: false } } do %>
  <span class="icon_heart_alt"></span>
<% end %>

  </li>
  <li><a href="#"><span class="icon_adjust-horiz"></span></a></li>
</ul>
            
          </div>
      <% selected_variant_ids = default_combination.product_variants.pluck(:id) %>

          <!-- Product Variants -->
          <div class="product__details__widget">
            <ul>
              <li>
                <span>Available color:</span>
                <div class="color__checkbox">
                  <% (@variant_options["Color"] || []).each do |option| %>
                    <label>
                      <input type="radio"
       name="color"
       value="<%= option.id %>"
       class="variant-option"
       data-type="Color"
       <%= "checked" if selected_variant_ids.include?(option.id) %>>

                      <span class="checkmark <%= option.value.downcase %>-bg"></span>
                    </label>
                  <% end %>
                </div>
              </li>
              
              <li>
                <span>Available size:</span>
                <div class="size__btn">
                  <% (@variant_options["Size"] || []).each do |option| %>
                    <label>
                     <input type="radio"
       name="size"
       value="<%= option.id %>"
       class="variant-option"
       data-type="Size"
       <%= "checked" if selected_variant_ids.include?(option.id) %>>
        
                      <%= option.value %>
                    </label>
                  <% end %> 
                </div>
              </li>
              <li>
                <span>Promotions:</span>
                <p>Free shipping</p>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Tabs -->
      <div class="col-lg-12">
        <div class="product__details__tab">
          <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Description</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab">Specification</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#tabs-3" role="tab">Reviews ( 2 )</a>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active" id="tabs-1" role="tabpanel">
              <h6>Description</h6>
              <p><%= @product.description %></p>
            </div>
            <div class="tab-pane" id="tabs-2" role="tabpanel">
              <h6>Specification</h6>
              <p><%= @product.specification %></p>
            </div>
            <div class="tab-pane" id="tabs-3" role="tabpanel">
              <h6>Reviews ( 2 )</h6>
              <p>Sample reviews here...</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Related Products -->
           
    </div><div class="row">
                <div class="col-lg-12 text-center">
                    <div class="related__title">
                        <h5>RELATED PRODUCTS</h5>
                    </div>
                </div>
                 <% @related_products.each do |product| %>
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="<%= url_for(product.featured_image) if product.featured_image.attached? %>">
                            <div class="label new">New</div>
                              <ul class="product__hover">
                <li>
                  <a href="<%= url_for(product.featured_image) if product.featured_image.attached? %>" class="image-popup">
                    <span class="arrow_expand"></span>
                  </a>
                </li>

                
 <li>
    <a  class="wishlist-btn" data-product-id="<%= product.id %>">
      <span class="icon_heart_alt"></span>
    </a>
  </li>

  <!-- Add to cart -->
  <li>
    <a  class="add-to-cart-btn" data-variant-id="<%= product.default_variant_combination.id %>">
      <span class="icon_bag_alt"></span>
    </a>
  </li>
                <%# Wishlist button %>
               
                <%# Add to cart button %>
            
              </ul>
                        </div>
                        <div class="product__item__text">
                             <h6><%= link_to product.name, product_path(product) %>
</h6>
                            <div class="rating">
                <% 5.times do %>
                  <i class="fa fa-star"></i>
                <% end %>
              </div>
                            <% combo = product.product_variant_combinations.first %>

<div class="product__price">
 $ <%= combo.price if combo %>

  <% if combo&.compared_price.present? &&
        combo.compared_price > combo.price %>
    <span>$ <%= combo.compared_price %></span>
  <% end %>
</div>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
  </div>
</section>

<script>

  window.variantCombinations = <%= raw @variant_combinations.to_json(
    only: [:id, :price, :compared_price],
    include: {
      product_variants: {
        only: [:id],
        methods: [:variant_type]
      }
    }
  ) %>;
  </script>

  <script>



  const selectedOptions = {};

  document.querySelectorAll(".variant-option").forEach(input => {
    input.addEventListener("change", () => {
      selectedOptions[input.dataset.type] = parseInt(input.value);
      updateVariant();
    });
  });

  function updateVariant() {
    const optionIds = Object.values(selectedOptions);

    // Require all options (Color + Size)
    if (optionIds.length < 2) return;

    const match = window.variantCombinations.find(combination => {
      const comboOptionIds = combination.product_variants.map(o => o.id);
      return optionIds.every(id => comboOptionIds.includes(id));
    });

    if (!match) return;

    // Update price
    document.getElementById("product-price").innerText = match.price;

    const compared = document.getElementById("compared-price");
    
      compared.innerText = `$ ${match.compared_price}`;
      compared.style.display = "inline";
   
    // Update hidden variant ID
    document.getElementById("selected-variant-id").value = match.id;
  }



</script>

<script>
document.addEventListener("turbolinks:load", () => {

  // Add to Cart
  document.querySelectorAll(".add-to-cart-btn").forEach(btn => {
    btn.addEventListener("click", e => {
      e.preventDefault();
      const variantId = btn.dataset.variantId;
      
      fetch("/line_items", {
        method: "POST",
        headers: {
          "X-CSRF-Token": document.querySelector("meta[name=csrf-token]").content,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ quantity: 1, product_variant_combination_id: variantId })
      })
      .then(res => res.json())
      .then(data => {
        if (data.success) {
          alert("Added to cart 🛒");
          document.getElementById("cart-count").innerText = data.cart_count;
        }
      });
    });
  });


  // Add to Wishlist
  document.querySelectorAll(".wishlist-btn").forEach(btn => {
    btn.addEventListener("click", e => {
      e.preventDefault();
      const productId = btn.dataset.productId;

      fetch("/wishlist_items", {
        method: "POST",
        headers: {
          "X-CSRF-Token": document.querySelector("meta[name=csrf-token]").content,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ product_id: productId })
      })
      .then(res => res.json())
      .then(data => {
        if (data.success) {
          alert("Added to wishlist ❤️");
        }
      });
    });
  });

});

</script>